version: '3.8'

services:
  # HTTP server (Node.js)
  http_server:
    build:
      context: .
      dockerfile: docker/http-server/Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env  # Ավելացնել սա
    depends_on:
      - postgres
      - mongo
      - redis

  # PostgreSQL
  postgres:
    build:
      context: .
      dockerfile: docker/pg-sql/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1596
      - POSTGRES_DB=test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # MongoDB
  mongo:
    build:
      context: .
      dockerfile: docker/mongo-db/Dockerfile
    environment:
      - MONGO_INITDB_DATABASE=test
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # Redis
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongo_data:
  redis_data:

name: test